stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

before_script:
  - pip install tox

test_python34:
  stage: test
  image: python:3.4
  script: tox --skip-missing-interpreters

test_python35:
  stage: test
  image: python:3.5
  script: tox --skip-missing-interpreters

test_python36:
  stage: test
  image: python:3.6
  script: tox --skip-missing-interpreters
